CREATE TABLE `abilities` (
	`ability_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`ability_nm` text NOT NULL,
	`ability_type` text,
	`ability_lcls` text,
	`ability_expln` text,
	`trgt_type` text,
	`dmg_type` text,
	`stat_eff_type` text,
	`use_cost` text,
	`cool_time` integer,
	`cast_time` integer,
	`use_cnd` text,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text
);
--> statement-breakpoint
CREATE TABLE `char_ability_maps` (
	`char_no` integer NOT NULL,
	`ability_no` integer NOT NULL,
	`ability_type` text NOT NULL,
	`prof_lvl` integer,
	`ability_rmk` text,
	PRIMARY KEY(`char_no`, `ability_no`, `ability_type`),
	FOREIGN KEY (`char_no`) REFERENCES `characters`(`char_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `char_trait_maps` (
	`char_no` integer NOT NULL,
	`trait_no` integer NOT NULL,
	`trait_type` text NOT NULL,
	`trait_rmk` text,
	PRIMARY KEY(`char_no`, `trait_no`, `trait_type`),
	FOREIGN KEY (`char_no`) REFERENCES `characters`(`char_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `characters` (
	`char_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`prj_no` integer NOT NULL,
	`char_nm` text NOT NULL,
	`alias_nm` text,
	`role_type` text,
	`logline` text,
	`narr_func` text,
	`race_no` integer,
	`ntn_no` integer,
	`org_no` integer,
	`org_rank` text,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text,
	FOREIGN KEY (`prj_no`) REFERENCES `projects`(`prj_no`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`race_no`) REFERENCES `creatures`(`creature_no`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`ntn_no`) REFERENCES `nations`(`ntn_no`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`org_no`) REFERENCES `organizations`(`org_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `core_rules` (
	`core_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`prj_no` integer NOT NULL,
	`core_nm` text NOT NULL,
	`def_desc` text,
	`aply_scope` text,
	`strc_elem` text,
	`mech_desc` text,
	`narr_aply` text,
	`keywords` text,
	`link_docs` text,
	`rmk` text,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text,
	FOREIGN KEY (`prj_no`) REFERENCES `projects`(`prj_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `creature_ability_maps` (
	`map_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`creature_no` integer NOT NULL,
	`ability_no` integer NOT NULL,
	`ability_type` text NOT NULL,
	`prof_lvl` integer,
	`ability_rmk` text,
	FOREIGN KEY (`creature_no`) REFERENCES `creatures`(`creature_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `creature_trait_maps` (
	`map_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`creature_no` integer NOT NULL,
	`trait_no` integer NOT NULL,
	`trait_type` text NOT NULL,
	`trait_rmk` text,
	FOREIGN KEY (`creature_no`) REFERENCES `creatures`(`creature_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `creatures` (
	`creature_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`prj_no` integer NOT NULL,
	`creature_nm` text NOT NULL,
	`creature_type` text,
	`danger_grd` text,
	`ident_stat` text,
	`creature_expln` text,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text,
	FOREIGN KEY (`prj_no`) REFERENCES `projects`(`prj_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `events` (
	`event_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`prj_no` integer NOT NULL,
	`event_nm` text NOT NULL,
	`occur_time` text,
	`occur_loc` text,
	`smry` text,
	`cause_pub` text,
	`cause_real` text,
	`side_a_char` text,
	`side_a_org` text,
	`side_a_ntn` text,
	`side_b_char` text,
	`side_b_org` text,
	`side_b_ntn` text,
	`side_c_char` text,
	`side_c_org` text,
	`side_c_ntn` text,
	`flow_trgr` text,
	`flow_crisis` text,
	`flow_climax` text,
	`flow_concl` text,
	`dmg_rslt` text,
	`soc_chng` text,
	`curr_conn` text,
	`rec_official` text,
	`truth_hid` text,
	`rmk` text,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text,
	FOREIGN KEY (`prj_no`) REFERENCES `projects`(`prj_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `items` (
	`item_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`prj_no` integer NOT NULL,
	`item_nm` text NOT NULL,
	`cls_main` text,
	`cls_sub` text,
	`item_grd` text,
	`logline` text,
	`app_desc` text,
	`visual_feat` text,
	`attr_type` text,
	`dmg_type` text,
	`main_func` text,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text,
	FOREIGN KEY (`prj_no`) REFERENCES `projects`(`prj_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `lores` (
	`lore_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`prj_no` integer NOT NULL,
	`lore_nm` text NOT NULL,
	`lore_type` text,
	`main_subj` text,
	`smry` text,
	`trans_mthd` text,
	`pub_perc` text,
	`lore_plot` text,
	`real_fact` text,
	`dist_rsn` text,
	`diff_desc` text,
	`cltr_impact` text,
	`plot_conn` text,
	`rmk` text,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text,
	FOREIGN KEY (`prj_no`) REFERENCES `projects`(`prj_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `nations` (
	`ntn_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`prj_no` integer NOT NULL,
	`ntn_nm` text NOT NULL,
	`ntn_type` text,
	`logline` text,
	`capital_nm` text,
	`ruler_txt` text,
	`pol_sys` text,
	`admin_law` text,
	`state_rlgn` text,
	`rlgn_desc` text,
	`nat_idlg` text,
	`main_plcy` text,
	`taboo_act` text,
	`dipl_plcy` text,
	`intr_cnfl` text,
	`hidden_fact` text,
	`econ_struct` text,
	`soc_cltr` text,
	`mil_pwr` text,
	`hist_desc` text,
	`curr_issue` text,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text,
	FOREIGN KEY (`prj_no`) REFERENCES `projects`(`prj_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `organizations` (
	`org_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`prj_no` integer NOT NULL,
	`org_nm` text NOT NULL,
	`org_type` text,
	`logline` text,
	`org_theme` text,
	`purp_pub` text,
	`purp_hid` text,
	`fnd_bg` text,
	`org_strc` text,
	`org_scale` text,
	`join_cond` text,
	`exit_rule` text,
	`main_act` text,
	`act_area` text,
	`act_mthd` text,
	`fund_src` text,
	`key_fig` text,
	`hist_desc` text,
	`curr_stat` text,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text,
	FOREIGN KEY (`prj_no`) REFERENCES `projects`(`prj_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `project_abilities` (
	`ability_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`prj_no` integer NOT NULL,
	`ability_nm` text NOT NULL,
	`ability_type` text,
	`ability_lcls` text,
	`ability_expln` text,
	`trgt_type` text,
	`dmg_type` text,
	`stat_eff_type` text,
	`use_cost` text,
	`cool_time` integer,
	`cast_time` integer,
	`use_cnd` text,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text,
	FOREIGN KEY (`prj_no`) REFERENCES `projects`(`prj_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `project_traits` (
	`trait_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`prj_no` integer NOT NULL,
	`trait_nm` text NOT NULL,
	`trait_expln` text,
	`trait_lcls` text,
	`trait_mcls` text,
	`aply_trgt` text,
	`cnfl_trait_no` integer,
	`cnfl_trait_type` text,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text,
	FOREIGN KEY (`prj_no`) REFERENCES `projects`(`prj_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `projects` (
	`prj_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_no` integer NOT NULL,
	`prj_nm` text NOT NULL,
	`genre_type` text,
	`prj_desc` text,
	`cvr_img_url` text,
	`prj_expln` text,
	`prj_ver` text,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text,
	FOREIGN KEY (`user_no`) REFERENCES `users`(`user_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `regions` (
	`region_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`prj_no` integer NOT NULL,
	`up_region_no` integer,
	`region_nm` text NOT NULL,
	`region_type` text,
	`explor_stat` text,
	`region_expln` text,
	`loc_desc` text,
	`climate_env` text,
	`terrain_feat` text,
	`env_spec` text,
	`func_feat` text,
	`danger_lvl` text,
	`danger_fctr` text,
	`inhabit_info` text,
	`unknown_entity` text,
	`main_fclty` text,
	`rsrc_list` text,
	`ntn_no` integer,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text,
	FOREIGN KEY (`prj_no`) REFERENCES `projects`(`prj_no`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`up_region_no`) REFERENCES `regions`(`region_no`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`ntn_no`) REFERENCES `nations`(`ntn_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `traits` (
	`trait_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`trait_nm` text NOT NULL,
	`trait_expln` text,
	`trait_lcls` text,
	`trait_mcls` text,
	`aply_trgt` text,
	`cnfl_trait_no` integer,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text,
	FOREIGN KEY (`cnfl_trait_no`) REFERENCES `traits`(`trait_no`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `users` (
	`user_no` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_eml` text NOT NULL,
	`user_nm` text,
	`user_role` text,
	`profl_img_url` text,
	`biogp` text,
	`enpswd` text,
	`resh_token` text,
	`acnt_lck_yn` text,
	`lgn_fail_nmtm` integer,
	`last_lgn_dt` text,
	`last_lgn_ip` text,
	`last_pswd_chg_dt` text,
	`eml_auth_yn` text,
	`mkt_recp_agre_yn` text,
	`use_yn` text DEFAULT 'Y',
	`shrn_yn` text DEFAULT 'N',
	`del_yn` text DEFAULT 'N',
	`crt_no` integer,
	`crt_dt` text,
	`updt_no` integer,
	`updt_dt` text,
	`del_no` integer,
	`del_dt` text
);
