/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLoadingScreen: typeof import('./components/common/AppLoadingScreen.vue')['default']
    AppSidebar: typeof import('./components/common/AppSidebar.vue')['default']
    AppTitlebar: typeof import('./components/common/AppTitlebar.vue')['default']
    CategoryListSidebar: typeof import('./components/common/CategoryListSidebar.vue')['default']
    CommonButton: typeof import('./components/form/CommonButton.vue')['default']
    ContentHeader: typeof import('./components/common/ContentHeader.vue')['default']
    DetailField: typeof import('./components/common/DetailField.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    FormInput: typeof import('./components/form/FormInput.vue')['default']
    FormTextarea: typeof import('./components/form/FormTextarea.vue')['default']
    IconButton: typeof import('./components/form/IconButton.vue')['default']
    LoreDetailLayout: typeof import('./components/layouts/LoreDetailLayout.vue')['default']
    LoreListLayout: typeof import('./components/layouts/LoreListLayout.vue')['default']
    ProjectMenuLayout: typeof import('./components/layouts/ProjectMenuLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingItemCard: typeof import('./components/common/SettingItemCard.vue')['default']
    SettingSidebar: typeof import('./components/common/SettingSidebar.vue')['default']
    TagField: typeof import('./components/common/TagField.vue')['default']
    Template: typeof import('./components/template.vue')['default']
    ToggleTheme: typeof import('./components/common/ToggleTheme.vue')['default']
    VueIcon: typeof import('./components/common/VueIcon.vue')['default']
  }
}
